name = "TimeFrames"
uuid = "51948d2b-02eb-5b28-9840-c902cc6821c9"
authors = ["FemtoTrader <femto.trader@gmail.com>"]
version = "0.7.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Dates = "1.10.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
